
export const images ={
        logo: require('../../assets/images/rsz_logo33-03.jpg'),
        network:require('../../assets/images/Network.jpg'),
        avatar1:require('../../assets/images/1.png'),
        avatar2:require('../../assets/images/2.png'),
        avatar3:require('../../assets/images/3.png'),
        avatar4:require('../../assets/images/4.png'),
        avatar5:require('../../assets/images/5.png'),
        avatar6:require('../../assets/images/6.png'),
        avatar7:require('../../assets/images/7.png'),
        avatar8:require('../../assets/images/8.png'),
        avatar9:require('../../assets/images/9.png'),
        wikiLogo:require('../../assets/images/WikipediaPuzzle.png'),
        bouncyWikiLogo:require('../../assets/images/Bouncywikilogo.gif'),
        celebrityLogo:require('../../assets/images/CelebrityCategory.gif'),
        filmLogo:require('../../assets/images/filmCategory.gif'),
        musicLogo:require('../../assets/images/musicGif.gif'),
        nbaLogo:require('../../assets/images/NBAcategory.png'),
        politicsLogo:require('../../assets/images/PoliticsCategory.png'),
        generalKnowledgeLogo:require('../../assets/images/GeneralKnowPic.jpg'),
        generalKnowledgeGifLogo:require('../../assets/images/GeneralKnowledgeGif.gif'),
        bomb:require('../../assets/images/BOMBS.png'),
        cash:require('../../assets/images/money.png'),
        prize:require('../../assets/images/WINS.png'),
        dice:require('../../assets/images/dices.png'),
        dollar_coins:require('../../assets/images/CashMole.png'),
        microphone:require('../../assets/images/microphone.png'),
        trophy:require('../../assets/images/trophy.png'),
        expert:require('../../assets/images/expert.png'),
        bomb1:require('../../assets/images/1Bomb.png'),
        bomb3:require('../../assets/images/3Bombs.png'),
        bomb5:require('../../assets/images/5Bombs.png'),
        bomb7:require('../../assets/images/7Bombs.png'),
        SIXDOW:require('../../assets/images/SixDegreesOfWikipedia.png'),
        noImage: require('../../assets/images/noImage.png'),
        path:require('../../assets/images/vertex-path.png'),
        networkgIF:require('../../assets/images/animat-network-color.gif'),
}